# Generated by Django 4.0.3 on 2022-04-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('person_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('person_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='q2.lives')),
            ],
        ),
    ]
