# Generated by Django 2.2.28 on 2022-04-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.QuestionModel')),
            ],
        ),
    ]
